project -new
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Arrangement/Arrangement.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/LCD_Display/LCD_Display.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Mark/mark.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/uart_tx/uart_transfer.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/uart_tx/uart_test.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/uart_tx/precise_divider.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/DHT11/DHT11_top.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/DHT11/DHT11_opera.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/DHT11/DHT11_cmd.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/DHT11/async_send.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/bintobcd/bintobcd.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/GY_MCU90640/RAM.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/GY_MCU90640/uart_rx.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/GY_MCU90640/Process.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/ADC/AD7928.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Oxygen/Oxygen.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/sensor/sensor.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/LCD_Driver/LCD_Driver.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Video_Image_Processor_2/VIP_Matrix_Generate_3X3_1Bit.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Video_Image_Processor_2/VIP_Bit_Erosion_Detector.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Video_Image_Processor_2/VIP_Bit_Dilation_Detector.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Video_Image_Processor_2/Line_Shift_RAM_1Bit.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Video_Image_Processor_2/Image_Handler.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Sdram_Control_2Port/Sdram_WR_FIFO.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Sdram_Control_2Port/Sdram_RD_FIFO.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Sdram_Control_2Port/Sdram_Control_2Port.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Sdram_Control_2Port/sdr_data_path.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Sdram_Control_2Port/control_interface.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Sdram_Control_2Port/command.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/key/Threshold_Adj.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/key/key_counter_scan.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Image_Algorithm/Image_Handler.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Sensor_Image_Zoom/Sensor_Image_Zoom.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/SingleSensorDriver_MT9V034/SingleSensorDriver_MT9V034.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/cmos_i2c_oVxxxx/i2c_timing_ctrl_16bit.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/cmos_i2c_oVxxxx/I2C_MT9V034_Gray_Config.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/cmos_i2c_oVxxxx/CMOS_Capture_RAW_Gray.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Video_Image_Processor/VIP_Matrix_Generate_3X3_8Bit.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Video_Image_Processor/VIP_Gray_Mean_Filter.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Video_Image_Processor/Video_Image_Processor.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Video_Image_Processor/Line_Shift_RAM_8Bit.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/system_index/system_init_delay.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/system_index/system_ctrl_pll.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/FAMS.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/system_index/pll.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/Body_temp_Process/Body_temp_Process.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_temp_unit.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_0.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_1.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_2.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_3.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_4.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_5.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_6.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_7.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_8.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_9.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_dp.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_chinese.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_ppm.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/rtl/key_control/key_control.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/ROM/ROM_rh.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/MULT/MULT_1.v}
add_file -verilog {E:/2019GEDC/CODE_Project/Cyclone_IV/FAMS/MULT/MULT_2.v}
add_file -constraint {FAMS.sdc}
set_option -top_module FAMS
set_option -technology CYCLONEIV-E
set_option -part EP4CE10
set_option -package FC17
set_option -speed_grade -8
set_option -write_verilog 0
set_option -write_vhdl 0
set_option -write_vif 0
set_option -write_apr_constraint 0
project -result_file ./FAMS.vqm
project -log_file ./FAMS.srr
set_option -frequency auto
project -run
project -save FAMS.prj
