// qsys_system.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module qsys_system (
		input  wire [11:0] ain_ch0_export,        //        ain_ch0.export
		input  wire [11:0] ain_ch1_export,        //        ain_ch1.export
		input  wire [11:0] ain_ch2_export,        //        ain_ch2.export
		input  wire [11:0] ain_ch3_export,        //        ain_ch3.export
		input  wire [11:0] ain_ch4_export,        //        ain_ch4.export
		input  wire        clk_clk,               //            clk.clk
		input  wire        end_o_export,          //          end_o.export
		output wire [3:0]  h2_one_export,         //         h2_one.export
		output wire [3:0]  h2_ten_export,         //         h2_ten.export
		output wire [3:0]  harmful_one_export,    //    harmful_one.export
		output wire [3:0]  harmful_ten_export,    //    harmful_ten.export
		output wire [3:0]  heart_rate_hun_export, // heart_rate_hun.export
		output wire [3:0]  heart_rate_one_export, // heart_rate_one.export
		output wire [3:0]  heart_rate_ten_export, // heart_rate_ten.export
		output wire [3:0]  liquefied_one_export,  //  liquefied_one.export
		output wire [3:0]  liquefied_ten_export,  //  liquefied_ten.export
		input  wire [23:0] max30102_0_export,     //     max30102_0.export
		input  wire [23:0] max30102_1_export,     //     max30102_1.export
		output wire [3:0]  natural_one_export,    //    natural_one.export
		output wire [3:0]  natural_ten_export,    //    natural_ten.export
		output wire [3:0]  oxy_one_export,        //        oxy_one.export
		output wire [3:0]  oxy_ten_export,        //        oxy_ten.export
		input  wire        reset_reset_n          //          reset.reset_n
	);

	wire  [31:0] nios2_gen2_data_master_readdata;                           // mm_interconnect_0:nios2_gen2_data_master_readdata -> nios2_gen2:d_readdata
	wire         nios2_gen2_data_master_waitrequest;                        // mm_interconnect_0:nios2_gen2_data_master_waitrequest -> nios2_gen2:d_waitrequest
	wire         nios2_gen2_data_master_debugaccess;                        // nios2_gen2:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:nios2_gen2_data_master_debugaccess
	wire  [16:0] nios2_gen2_data_master_address;                            // nios2_gen2:d_address -> mm_interconnect_0:nios2_gen2_data_master_address
	wire   [3:0] nios2_gen2_data_master_byteenable;                         // nios2_gen2:d_byteenable -> mm_interconnect_0:nios2_gen2_data_master_byteenable
	wire         nios2_gen2_data_master_read;                               // nios2_gen2:d_read -> mm_interconnect_0:nios2_gen2_data_master_read
	wire         nios2_gen2_data_master_write;                              // nios2_gen2:d_write -> mm_interconnect_0:nios2_gen2_data_master_write
	wire  [31:0] nios2_gen2_data_master_writedata;                          // nios2_gen2:d_writedata -> mm_interconnect_0:nios2_gen2_data_master_writedata
	wire  [31:0] nios2_gen2_instruction_master_readdata;                    // mm_interconnect_0:nios2_gen2_instruction_master_readdata -> nios2_gen2:i_readdata
	wire         nios2_gen2_instruction_master_waitrequest;                 // mm_interconnect_0:nios2_gen2_instruction_master_waitrequest -> nios2_gen2:i_waitrequest
	wire  [16:0] nios2_gen2_instruction_master_address;                     // nios2_gen2:i_address -> mm_interconnect_0:nios2_gen2_instruction_master_address
	wire         nios2_gen2_instruction_master_read;                        // nios2_gen2:i_read -> mm_interconnect_0:nios2_gen2_instruction_master_read
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:jtag_uart_avalon_jtag_slave_chipselect -> jtag_uart:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata;    // jtag_uart:av_readdata -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest; // jtag_uart:av_waitrequest -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_address;     // mm_interconnect_0:jtag_uart_avalon_jtag_slave_address -> jtag_uart:av_address
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;        // mm_interconnect_0:jtag_uart_avalon_jtag_slave_read -> jtag_uart:av_read_n
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;       // mm_interconnect_0:jtag_uart_avalon_jtag_slave_write -> jtag_uart:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata;   // mm_interconnect_0:jtag_uart_avalon_jtag_slave_writedata -> jtag_uart:av_writedata
	wire  [31:0] mm_interconnect_0_sysid_qsys_control_slave_readdata;       // sysid_qsys:readdata -> mm_interconnect_0:sysid_qsys_control_slave_readdata
	wire   [0:0] mm_interconnect_0_sysid_qsys_control_slave_address;        // mm_interconnect_0:sysid_qsys_control_slave_address -> sysid_qsys:address
	wire  [31:0] mm_interconnect_0_nios2_gen2_debug_mem_slave_readdata;     // nios2_gen2:debug_mem_slave_readdata -> mm_interconnect_0:nios2_gen2_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios2_gen2_debug_mem_slave_waitrequest;  // nios2_gen2:debug_mem_slave_waitrequest -> mm_interconnect_0:nios2_gen2_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios2_gen2_debug_mem_slave_debugaccess;  // mm_interconnect_0:nios2_gen2_debug_mem_slave_debugaccess -> nios2_gen2:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios2_gen2_debug_mem_slave_address;      // mm_interconnect_0:nios2_gen2_debug_mem_slave_address -> nios2_gen2:debug_mem_slave_address
	wire         mm_interconnect_0_nios2_gen2_debug_mem_slave_read;         // mm_interconnect_0:nios2_gen2_debug_mem_slave_read -> nios2_gen2:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios2_gen2_debug_mem_slave_byteenable;   // mm_interconnect_0:nios2_gen2_debug_mem_slave_byteenable -> nios2_gen2:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios2_gen2_debug_mem_slave_write;        // mm_interconnect_0:nios2_gen2_debug_mem_slave_write -> nios2_gen2:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios2_gen2_debug_mem_slave_writedata;    // mm_interconnect_0:nios2_gen2_debug_mem_slave_writedata -> nios2_gen2:debug_mem_slave_writedata
	wire         mm_interconnect_0_ram_s1_chipselect;                       // mm_interconnect_0:RAM_s1_chipselect -> RAM:chipselect
	wire  [31:0] mm_interconnect_0_ram_s1_readdata;                         // RAM:readdata -> mm_interconnect_0:RAM_s1_readdata
	wire  [12:0] mm_interconnect_0_ram_s1_address;                          // mm_interconnect_0:RAM_s1_address -> RAM:address
	wire   [3:0] mm_interconnect_0_ram_s1_byteenable;                       // mm_interconnect_0:RAM_s1_byteenable -> RAM:byteenable
	wire         mm_interconnect_0_ram_s1_write;                            // mm_interconnect_0:RAM_s1_write -> RAM:write
	wire  [31:0] mm_interconnect_0_ram_s1_writedata;                        // mm_interconnect_0:RAM_s1_writedata -> RAM:writedata
	wire         mm_interconnect_0_ram_s1_clken;                            // mm_interconnect_0:RAM_s1_clken -> RAM:clken
	wire  [31:0] mm_interconnect_0_max30102_0_s1_readdata;                  // max30102_0:readdata -> mm_interconnect_0:max30102_0_s1_readdata
	wire   [1:0] mm_interconnect_0_max30102_0_s1_address;                   // mm_interconnect_0:max30102_0_s1_address -> max30102_0:address
	wire  [31:0] mm_interconnect_0_max30102_1_s1_readdata;                  // max30102_1:readdata -> mm_interconnect_0:max30102_1_s1_readdata
	wire   [1:0] mm_interconnect_0_max30102_1_s1_address;                   // mm_interconnect_0:max30102_1_s1_address -> max30102_1:address
	wire  [31:0] mm_interconnect_0_end_o_s1_readdata;                       // end_o:readdata -> mm_interconnect_0:end_o_s1_readdata
	wire   [1:0] mm_interconnect_0_end_o_s1_address;                        // mm_interconnect_0:end_o_s1_address -> end_o:address
	wire         mm_interconnect_0_heart_rate_hun_s1_chipselect;            // mm_interconnect_0:heart_rate_hun_s1_chipselect -> heart_rate_hun:chipselect
	wire  [31:0] mm_interconnect_0_heart_rate_hun_s1_readdata;              // heart_rate_hun:readdata -> mm_interconnect_0:heart_rate_hun_s1_readdata
	wire   [1:0] mm_interconnect_0_heart_rate_hun_s1_address;               // mm_interconnect_0:heart_rate_hun_s1_address -> heart_rate_hun:address
	wire         mm_interconnect_0_heart_rate_hun_s1_write;                 // mm_interconnect_0:heart_rate_hun_s1_write -> heart_rate_hun:write_n
	wire  [31:0] mm_interconnect_0_heart_rate_hun_s1_writedata;             // mm_interconnect_0:heart_rate_hun_s1_writedata -> heart_rate_hun:writedata
	wire         mm_interconnect_0_heart_rate_one_s1_chipselect;            // mm_interconnect_0:heart_rate_one_s1_chipselect -> heart_rate_one:chipselect
	wire  [31:0] mm_interconnect_0_heart_rate_one_s1_readdata;              // heart_rate_one:readdata -> mm_interconnect_0:heart_rate_one_s1_readdata
	wire   [1:0] mm_interconnect_0_heart_rate_one_s1_address;               // mm_interconnect_0:heart_rate_one_s1_address -> heart_rate_one:address
	wire         mm_interconnect_0_heart_rate_one_s1_write;                 // mm_interconnect_0:heart_rate_one_s1_write -> heart_rate_one:write_n
	wire  [31:0] mm_interconnect_0_heart_rate_one_s1_writedata;             // mm_interconnect_0:heart_rate_one_s1_writedata -> heart_rate_one:writedata
	wire         mm_interconnect_0_heart_rate_ten_s1_chipselect;            // mm_interconnect_0:heart_rate_ten_s1_chipselect -> heart_rate_ten:chipselect
	wire  [31:0] mm_interconnect_0_heart_rate_ten_s1_readdata;              // heart_rate_ten:readdata -> mm_interconnect_0:heart_rate_ten_s1_readdata
	wire   [1:0] mm_interconnect_0_heart_rate_ten_s1_address;               // mm_interconnect_0:heart_rate_ten_s1_address -> heart_rate_ten:address
	wire         mm_interconnect_0_heart_rate_ten_s1_write;                 // mm_interconnect_0:heart_rate_ten_s1_write -> heart_rate_ten:write_n
	wire  [31:0] mm_interconnect_0_heart_rate_ten_s1_writedata;             // mm_interconnect_0:heart_rate_ten_s1_writedata -> heart_rate_ten:writedata
	wire  [31:0] mm_interconnect_0_ain_ch4_s1_readdata;                     // ain_ch4:readdata -> mm_interconnect_0:ain_ch4_s1_readdata
	wire   [1:0] mm_interconnect_0_ain_ch4_s1_address;                      // mm_interconnect_0:ain_ch4_s1_address -> ain_ch4:address
	wire  [31:0] mm_interconnect_0_ain_ch3_s1_readdata;                     // ain_ch3:readdata -> mm_interconnect_0:ain_ch3_s1_readdata
	wire   [1:0] mm_interconnect_0_ain_ch3_s1_address;                      // mm_interconnect_0:ain_ch3_s1_address -> ain_ch3:address
	wire  [31:0] mm_interconnect_0_ain_ch2_s1_readdata;                     // ain_ch2:readdata -> mm_interconnect_0:ain_ch2_s1_readdata
	wire   [1:0] mm_interconnect_0_ain_ch2_s1_address;                      // mm_interconnect_0:ain_ch2_s1_address -> ain_ch2:address
	wire  [31:0] mm_interconnect_0_ain_ch1_s1_readdata;                     // ain_ch1:readdata -> mm_interconnect_0:ain_ch1_s1_readdata
	wire   [1:0] mm_interconnect_0_ain_ch1_s1_address;                      // mm_interconnect_0:ain_ch1_s1_address -> ain_ch1:address
	wire  [31:0] mm_interconnect_0_ain_ch0_s1_readdata;                     // ain_ch0:readdata -> mm_interconnect_0:ain_ch0_s1_readdata
	wire   [1:0] mm_interconnect_0_ain_ch0_s1_address;                      // mm_interconnect_0:ain_ch0_s1_address -> ain_ch0:address
	wire         mm_interconnect_0_h2_ten_s1_chipselect;                    // mm_interconnect_0:h2_ten_s1_chipselect -> h2_ten:chipselect
	wire  [31:0] mm_interconnect_0_h2_ten_s1_readdata;                      // h2_ten:readdata -> mm_interconnect_0:h2_ten_s1_readdata
	wire   [1:0] mm_interconnect_0_h2_ten_s1_address;                       // mm_interconnect_0:h2_ten_s1_address -> h2_ten:address
	wire         mm_interconnect_0_h2_ten_s1_write;                         // mm_interconnect_0:h2_ten_s1_write -> h2_ten:write_n
	wire  [31:0] mm_interconnect_0_h2_ten_s1_writedata;                     // mm_interconnect_0:h2_ten_s1_writedata -> h2_ten:writedata
	wire         mm_interconnect_0_h2_one_s1_chipselect;                    // mm_interconnect_0:h2_one_s1_chipselect -> h2_one:chipselect
	wire  [31:0] mm_interconnect_0_h2_one_s1_readdata;                      // h2_one:readdata -> mm_interconnect_0:h2_one_s1_readdata
	wire   [1:0] mm_interconnect_0_h2_one_s1_address;                       // mm_interconnect_0:h2_one_s1_address -> h2_one:address
	wire         mm_interconnect_0_h2_one_s1_write;                         // mm_interconnect_0:h2_one_s1_write -> h2_one:write_n
	wire  [31:0] mm_interconnect_0_h2_one_s1_writedata;                     // mm_interconnect_0:h2_one_s1_writedata -> h2_one:writedata
	wire         mm_interconnect_0_liquefied_ten_s1_chipselect;             // mm_interconnect_0:liquefied_ten_s1_chipselect -> liquefied_ten:chipselect
	wire  [31:0] mm_interconnect_0_liquefied_ten_s1_readdata;               // liquefied_ten:readdata -> mm_interconnect_0:liquefied_ten_s1_readdata
	wire   [1:0] mm_interconnect_0_liquefied_ten_s1_address;                // mm_interconnect_0:liquefied_ten_s1_address -> liquefied_ten:address
	wire         mm_interconnect_0_liquefied_ten_s1_write;                  // mm_interconnect_0:liquefied_ten_s1_write -> liquefied_ten:write_n
	wire  [31:0] mm_interconnect_0_liquefied_ten_s1_writedata;              // mm_interconnect_0:liquefied_ten_s1_writedata -> liquefied_ten:writedata
	wire         mm_interconnect_0_liquefied_one_s1_chipselect;             // mm_interconnect_0:liquefied_one_s1_chipselect -> liquefied_one:chipselect
	wire  [31:0] mm_interconnect_0_liquefied_one_s1_readdata;               // liquefied_one:readdata -> mm_interconnect_0:liquefied_one_s1_readdata
	wire   [1:0] mm_interconnect_0_liquefied_one_s1_address;                // mm_interconnect_0:liquefied_one_s1_address -> liquefied_one:address
	wire         mm_interconnect_0_liquefied_one_s1_write;                  // mm_interconnect_0:liquefied_one_s1_write -> liquefied_one:write_n
	wire  [31:0] mm_interconnect_0_liquefied_one_s1_writedata;              // mm_interconnect_0:liquefied_one_s1_writedata -> liquefied_one:writedata
	wire         mm_interconnect_0_natural_ten_s1_chipselect;               // mm_interconnect_0:natural_ten_s1_chipselect -> natural_ten:chipselect
	wire  [31:0] mm_interconnect_0_natural_ten_s1_readdata;                 // natural_ten:readdata -> mm_interconnect_0:natural_ten_s1_readdata
	wire   [1:0] mm_interconnect_0_natural_ten_s1_address;                  // mm_interconnect_0:natural_ten_s1_address -> natural_ten:address
	wire         mm_interconnect_0_natural_ten_s1_write;                    // mm_interconnect_0:natural_ten_s1_write -> natural_ten:write_n
	wire  [31:0] mm_interconnect_0_natural_ten_s1_writedata;                // mm_interconnect_0:natural_ten_s1_writedata -> natural_ten:writedata
	wire         mm_interconnect_0_natural_one_s1_chipselect;               // mm_interconnect_0:natural_one_s1_chipselect -> natural_one:chipselect
	wire  [31:0] mm_interconnect_0_natural_one_s1_readdata;                 // natural_one:readdata -> mm_interconnect_0:natural_one_s1_readdata
	wire   [1:0] mm_interconnect_0_natural_one_s1_address;                  // mm_interconnect_0:natural_one_s1_address -> natural_one:address
	wire         mm_interconnect_0_natural_one_s1_write;                    // mm_interconnect_0:natural_one_s1_write -> natural_one:write_n
	wire  [31:0] mm_interconnect_0_natural_one_s1_writedata;                // mm_interconnect_0:natural_one_s1_writedata -> natural_one:writedata
	wire         mm_interconnect_0_harmful_ten_s1_chipselect;               // mm_interconnect_0:harmful_ten_s1_chipselect -> harmful_ten:chipselect
	wire  [31:0] mm_interconnect_0_harmful_ten_s1_readdata;                 // harmful_ten:readdata -> mm_interconnect_0:harmful_ten_s1_readdata
	wire   [1:0] mm_interconnect_0_harmful_ten_s1_address;                  // mm_interconnect_0:harmful_ten_s1_address -> harmful_ten:address
	wire         mm_interconnect_0_harmful_ten_s1_write;                    // mm_interconnect_0:harmful_ten_s1_write -> harmful_ten:write_n
	wire  [31:0] mm_interconnect_0_harmful_ten_s1_writedata;                // mm_interconnect_0:harmful_ten_s1_writedata -> harmful_ten:writedata
	wire         mm_interconnect_0_harmful_one_s1_chipselect;               // mm_interconnect_0:harmful_one_s1_chipselect -> harmful_one:chipselect
	wire  [31:0] mm_interconnect_0_harmful_one_s1_readdata;                 // harmful_one:readdata -> mm_interconnect_0:harmful_one_s1_readdata
	wire   [1:0] mm_interconnect_0_harmful_one_s1_address;                  // mm_interconnect_0:harmful_one_s1_address -> harmful_one:address
	wire         mm_interconnect_0_harmful_one_s1_write;                    // mm_interconnect_0:harmful_one_s1_write -> harmful_one:write_n
	wire  [31:0] mm_interconnect_0_harmful_one_s1_writedata;                // mm_interconnect_0:harmful_one_s1_writedata -> harmful_one:writedata
	wire         mm_interconnect_0_oxy_ten_s1_chipselect;                   // mm_interconnect_0:oxy_ten_s1_chipselect -> oxy_ten:chipselect
	wire  [31:0] mm_interconnect_0_oxy_ten_s1_readdata;                     // oxy_ten:readdata -> mm_interconnect_0:oxy_ten_s1_readdata
	wire   [1:0] mm_interconnect_0_oxy_ten_s1_address;                      // mm_interconnect_0:oxy_ten_s1_address -> oxy_ten:address
	wire         mm_interconnect_0_oxy_ten_s1_write;                        // mm_interconnect_0:oxy_ten_s1_write -> oxy_ten:write_n
	wire  [31:0] mm_interconnect_0_oxy_ten_s1_writedata;                    // mm_interconnect_0:oxy_ten_s1_writedata -> oxy_ten:writedata
	wire         mm_interconnect_0_oxy_one_s1_chipselect;                   // mm_interconnect_0:oxy_one_s1_chipselect -> oxy_one:chipselect
	wire  [31:0] mm_interconnect_0_oxy_one_s1_readdata;                     // oxy_one:readdata -> mm_interconnect_0:oxy_one_s1_readdata
	wire   [1:0] mm_interconnect_0_oxy_one_s1_address;                      // mm_interconnect_0:oxy_one_s1_address -> oxy_one:address
	wire         mm_interconnect_0_oxy_one_s1_write;                        // mm_interconnect_0:oxy_one_s1_write -> oxy_one:write_n
	wire  [31:0] mm_interconnect_0_oxy_one_s1_writedata;                    // mm_interconnect_0:oxy_one_s1_writedata -> oxy_one:writedata
	wire         mm_interconnect_0_rom_s1_chipselect;                       // mm_interconnect_0:ROM_s1_chipselect -> ROM:chipselect
	wire  [31:0] mm_interconnect_0_rom_s1_readdata;                         // ROM:readdata -> mm_interconnect_0:ROM_s1_readdata
	wire         mm_interconnect_0_rom_s1_debugaccess;                      // mm_interconnect_0:ROM_s1_debugaccess -> ROM:debugaccess
	wire  [10:0] mm_interconnect_0_rom_s1_address;                          // mm_interconnect_0:ROM_s1_address -> ROM:address
	wire   [3:0] mm_interconnect_0_rom_s1_byteenable;                       // mm_interconnect_0:ROM_s1_byteenable -> ROM:byteenable
	wire         mm_interconnect_0_rom_s1_write;                            // mm_interconnect_0:ROM_s1_write -> ROM:write
	wire  [31:0] mm_interconnect_0_rom_s1_writedata;                        // mm_interconnect_0:ROM_s1_writedata -> ROM:writedata
	wire         mm_interconnect_0_rom_s1_clken;                            // mm_interconnect_0:ROM_s1_clken -> ROM:clken
	wire         irq_mapper_receiver0_irq;                                  // jtag_uart:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] nios2_gen2_irq_irq;                                        // irq_mapper:sender_irq -> nios2_gen2:irq
	wire         rst_controller_reset_out_reset;                            // rst_controller:reset_out -> [RAM:reset, ain_ch0:reset_n, ain_ch1:reset_n, ain_ch2:reset_n, ain_ch3:reset_n, ain_ch4:reset_n, end_o:reset_n, h2_one:reset_n, h2_ten:reset_n, harmful_one:reset_n, harmful_ten:reset_n, heart_rate_hun:reset_n, heart_rate_one:reset_n, heart_rate_ten:reset_n, irq_mapper:reset, jtag_uart:rst_n, liquefied_one:reset_n, liquefied_ten:reset_n, max30102_0:reset_n, max30102_1:reset_n, mm_interconnect_0:nios2_gen2_reset_reset_bridge_in_reset_reset, natural_one:reset_n, natural_ten:reset_n, nios2_gen2:reset_n, oxy_one:reset_n, oxy_ten:reset_n, rst_translator:in_reset, sysid_qsys:reset_n]
	wire         rst_controller_reset_out_reset_req;                        // rst_controller:reset_req -> [RAM:reset_req, nios2_gen2:reset_req, rst_translator:reset_req_in]
	wire         nios2_gen2_debug_reset_request_reset;                      // nios2_gen2:debug_reset_request -> rst_controller:reset_in1
	wire         rst_controller_001_reset_out_reset;                        // rst_controller_001:reset_out -> [ROM:reset, mm_interconnect_0:ROM_reset1_reset_bridge_in_reset_reset]
	wire         rst_controller_001_reset_out_reset_req;                    // rst_controller_001:reset_req -> ROM:reset_req

	qsys_system_RAM ram (
		.clk        (clk_clk),                             //   clk1.clk
		.address    (mm_interconnect_0_ram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_ram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_ram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_ram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_ram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_ram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_ram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),      // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),  //       .reset_req
		.freeze     (1'b0)                                 // (terminated)
	);

	qsys_system_ROM rom (
		.clk         (clk_clk),                                //   clk1.clk
		.address     (mm_interconnect_0_rom_s1_address),       //     s1.address
		.debugaccess (mm_interconnect_0_rom_s1_debugaccess),   //       .debugaccess
		.clken       (mm_interconnect_0_rom_s1_clken),         //       .clken
		.chipselect  (mm_interconnect_0_rom_s1_chipselect),    //       .chipselect
		.write       (mm_interconnect_0_rom_s1_write),         //       .write
		.readdata    (mm_interconnect_0_rom_s1_readdata),      //       .readdata
		.writedata   (mm_interconnect_0_rom_s1_writedata),     //       .writedata
		.byteenable  (mm_interconnect_0_rom_s1_byteenable),    //       .byteenable
		.reset       (rst_controller_001_reset_out_reset),     // reset1.reset
		.reset_req   (rst_controller_001_reset_out_reset_req), //       .reset_req
		.freeze      (1'b0)                                    // (terminated)
	);

	qsys_system_ain_ch0 ain_ch0 (
		.clk      (clk_clk),                               //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_ain_ch0_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_ain_ch0_s1_readdata), //                    .readdata
		.in_port  (ain_ch0_export)                         // external_connection.export
	);

	qsys_system_ain_ch0 ain_ch1 (
		.clk      (clk_clk),                               //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_ain_ch1_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_ain_ch1_s1_readdata), //                    .readdata
		.in_port  (ain_ch1_export)                         // external_connection.export
	);

	qsys_system_ain_ch0 ain_ch2 (
		.clk      (clk_clk),                               //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_ain_ch2_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_ain_ch2_s1_readdata), //                    .readdata
		.in_port  (ain_ch2_export)                         // external_connection.export
	);

	qsys_system_ain_ch0 ain_ch3 (
		.clk      (clk_clk),                               //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_ain_ch3_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_ain_ch3_s1_readdata), //                    .readdata
		.in_port  (ain_ch3_export)                         // external_connection.export
	);

	qsys_system_ain_ch0 ain_ch4 (
		.clk      (clk_clk),                               //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_ain_ch4_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_ain_ch4_s1_readdata), //                    .readdata
		.in_port  (ain_ch4_export)                         // external_connection.export
	);

	qsys_system_end_o end_o (
		.clk      (clk_clk),                             //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),     //               reset.reset_n
		.address  (mm_interconnect_0_end_o_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_end_o_s1_readdata), //                    .readdata
		.in_port  (end_o_export)                         // external_connection.export
	);

	qsys_system_h2_one h2_one (
		.clk        (clk_clk),                                //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address    (mm_interconnect_0_h2_one_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h2_one_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h2_one_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h2_one_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h2_one_s1_readdata),   //                    .readdata
		.out_port   (h2_one_export)                           // external_connection.export
	);

	qsys_system_h2_one h2_ten (
		.clk        (clk_clk),                                //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address    (mm_interconnect_0_h2_ten_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_h2_ten_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_h2_ten_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_h2_ten_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_h2_ten_s1_readdata),   //                    .readdata
		.out_port   (h2_ten_export)                           // external_connection.export
	);

	qsys_system_h2_one harmful_one (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_harmful_one_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_harmful_one_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_harmful_one_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_harmful_one_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_harmful_one_s1_readdata),   //                    .readdata
		.out_port   (harmful_one_export)                           // external_connection.export
	);

	qsys_system_h2_one harmful_ten (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_harmful_ten_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_harmful_ten_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_harmful_ten_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_harmful_ten_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_harmful_ten_s1_readdata),   //                    .readdata
		.out_port   (harmful_ten_export)                           // external_connection.export
	);

	qsys_system_h2_one heart_rate_hun (
		.clk        (clk_clk),                                        //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                //               reset.reset_n
		.address    (mm_interconnect_0_heart_rate_hun_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_heart_rate_hun_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_heart_rate_hun_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_heart_rate_hun_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_heart_rate_hun_s1_readdata),   //                    .readdata
		.out_port   (heart_rate_hun_export)                           // external_connection.export
	);

	qsys_system_h2_one heart_rate_one (
		.clk        (clk_clk),                                        //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                //               reset.reset_n
		.address    (mm_interconnect_0_heart_rate_one_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_heart_rate_one_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_heart_rate_one_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_heart_rate_one_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_heart_rate_one_s1_readdata),   //                    .readdata
		.out_port   (heart_rate_one_export)                           // external_connection.export
	);

	qsys_system_h2_one heart_rate_ten (
		.clk        (clk_clk),                                        //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                //               reset.reset_n
		.address    (mm_interconnect_0_heart_rate_ten_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_heart_rate_ten_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_heart_rate_ten_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_heart_rate_ten_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_heart_rate_ten_s1_readdata),   //                    .readdata
		.out_port   (heart_rate_ten_export)                           // external_connection.export
	);

	qsys_system_jtag_uart jtag_uart (
		.clk            (clk_clk),                                                   //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                           //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                   //               irq.irq
	);

	qsys_system_h2_one liquefied_one (
		.clk        (clk_clk),                                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address    (mm_interconnect_0_liquefied_one_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_liquefied_one_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_liquefied_one_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_liquefied_one_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_liquefied_one_s1_readdata),   //                    .readdata
		.out_port   (liquefied_one_export)                           // external_connection.export
	);

	qsys_system_h2_one liquefied_ten (
		.clk        (clk_clk),                                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address    (mm_interconnect_0_liquefied_ten_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_liquefied_ten_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_liquefied_ten_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_liquefied_ten_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_liquefied_ten_s1_readdata),   //                    .readdata
		.out_port   (liquefied_ten_export)                           // external_connection.export
	);

	qsys_system_max30102_0 max30102_0 (
		.clk      (clk_clk),                                  //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),          //               reset.reset_n
		.address  (mm_interconnect_0_max30102_0_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_max30102_0_s1_readdata), //                    .readdata
		.in_port  (max30102_0_export)                         // external_connection.export
	);

	qsys_system_max30102_0 max30102_1 (
		.clk      (clk_clk),                                  //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),          //               reset.reset_n
		.address  (mm_interconnect_0_max30102_1_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_max30102_1_s1_readdata), //                    .readdata
		.in_port  (max30102_1_export)                         // external_connection.export
	);

	qsys_system_h2_one natural_one (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_natural_one_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_natural_one_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_natural_one_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_natural_one_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_natural_one_s1_readdata),   //                    .readdata
		.out_port   (natural_one_export)                           // external_connection.export
	);

	qsys_system_h2_one natural_ten (
		.clk        (clk_clk),                                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_natural_ten_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_natural_ten_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_natural_ten_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_natural_ten_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_natural_ten_s1_readdata),   //                    .readdata
		.out_port   (natural_ten_export)                           // external_connection.export
	);

	qsys_system_nios2_gen2 nios2_gen2 (
		.clk                                 (clk_clk),                                                  //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                          //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                       //                          .reset_req
		.d_address                           (nios2_gen2_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios2_gen2_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios2_gen2_data_master_read),                              //                          .read
		.d_readdata                          (nios2_gen2_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios2_gen2_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios2_gen2_data_master_write),                             //                          .write
		.d_writedata                         (nios2_gen2_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (nios2_gen2_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios2_gen2_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios2_gen2_instruction_master_read),                       //                          .read
		.i_readdata                          (nios2_gen2_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios2_gen2_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (nios2_gen2_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios2_gen2_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios2_gen2_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios2_gen2_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios2_gen2_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios2_gen2_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios2_gen2_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios2_gen2_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios2_gen2_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios2_gen2_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                          // custom_instruction_master.readra
	);

	qsys_system_h2_one oxy_one (
		.clk        (clk_clk),                                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address    (mm_interconnect_0_oxy_one_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_oxy_one_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_oxy_one_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_oxy_one_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_oxy_one_s1_readdata),   //                    .readdata
		.out_port   (oxy_one_export)                           // external_connection.export
	);

	qsys_system_h2_one oxy_ten (
		.clk        (clk_clk),                                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address    (mm_interconnect_0_oxy_ten_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_oxy_ten_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_oxy_ten_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_oxy_ten_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_oxy_ten_s1_readdata),   //                    .readdata
		.out_port   (oxy_ten_export)                           // external_connection.export
	);

	qsys_system_sysid_qsys sysid_qsys (
		.clock    (clk_clk),                                             //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                     //         reset.reset_n
		.readdata (mm_interconnect_0_sysid_qsys_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sysid_qsys_control_slave_address)   //              .address
	);

	qsys_system_mm_interconnect_0 mm_interconnect_0 (
		.clk_clk_clk                                  (clk_clk),                                                   //                                clk_clk.clk
		.nios2_gen2_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                            // nios2_gen2_reset_reset_bridge_in_reset.reset
		.ROM_reset1_reset_bridge_in_reset_reset       (rst_controller_001_reset_out_reset),                        //       ROM_reset1_reset_bridge_in_reset.reset
		.nios2_gen2_data_master_address               (nios2_gen2_data_master_address),                            //                 nios2_gen2_data_master.address
		.nios2_gen2_data_master_waitrequest           (nios2_gen2_data_master_waitrequest),                        //                                       .waitrequest
		.nios2_gen2_data_master_byteenable            (nios2_gen2_data_master_byteenable),                         //                                       .byteenable
		.nios2_gen2_data_master_read                  (nios2_gen2_data_master_read),                               //                                       .read
		.nios2_gen2_data_master_readdata              (nios2_gen2_data_master_readdata),                           //                                       .readdata
		.nios2_gen2_data_master_write                 (nios2_gen2_data_master_write),                              //                                       .write
		.nios2_gen2_data_master_writedata             (nios2_gen2_data_master_writedata),                          //                                       .writedata
		.nios2_gen2_data_master_debugaccess           (nios2_gen2_data_master_debugaccess),                        //                                       .debugaccess
		.nios2_gen2_instruction_master_address        (nios2_gen2_instruction_master_address),                     //          nios2_gen2_instruction_master.address
		.nios2_gen2_instruction_master_waitrequest    (nios2_gen2_instruction_master_waitrequest),                 //                                       .waitrequest
		.nios2_gen2_instruction_master_read           (nios2_gen2_instruction_master_read),                        //                                       .read
		.nios2_gen2_instruction_master_readdata       (nios2_gen2_instruction_master_readdata),                    //                                       .readdata
		.ain_ch0_s1_address                           (mm_interconnect_0_ain_ch0_s1_address),                      //                             ain_ch0_s1.address
		.ain_ch0_s1_readdata                          (mm_interconnect_0_ain_ch0_s1_readdata),                     //                                       .readdata
		.ain_ch1_s1_address                           (mm_interconnect_0_ain_ch1_s1_address),                      //                             ain_ch1_s1.address
		.ain_ch1_s1_readdata                          (mm_interconnect_0_ain_ch1_s1_readdata),                     //                                       .readdata
		.ain_ch2_s1_address                           (mm_interconnect_0_ain_ch2_s1_address),                      //                             ain_ch2_s1.address
		.ain_ch2_s1_readdata                          (mm_interconnect_0_ain_ch2_s1_readdata),                     //                                       .readdata
		.ain_ch3_s1_address                           (mm_interconnect_0_ain_ch3_s1_address),                      //                             ain_ch3_s1.address
		.ain_ch3_s1_readdata                          (mm_interconnect_0_ain_ch3_s1_readdata),                     //                                       .readdata
		.ain_ch4_s1_address                           (mm_interconnect_0_ain_ch4_s1_address),                      //                             ain_ch4_s1.address
		.ain_ch4_s1_readdata                          (mm_interconnect_0_ain_ch4_s1_readdata),                     //                                       .readdata
		.end_o_s1_address                             (mm_interconnect_0_end_o_s1_address),                        //                               end_o_s1.address
		.end_o_s1_readdata                            (mm_interconnect_0_end_o_s1_readdata),                       //                                       .readdata
		.h2_one_s1_address                            (mm_interconnect_0_h2_one_s1_address),                       //                              h2_one_s1.address
		.h2_one_s1_write                              (mm_interconnect_0_h2_one_s1_write),                         //                                       .write
		.h2_one_s1_readdata                           (mm_interconnect_0_h2_one_s1_readdata),                      //                                       .readdata
		.h2_one_s1_writedata                          (mm_interconnect_0_h2_one_s1_writedata),                     //                                       .writedata
		.h2_one_s1_chipselect                         (mm_interconnect_0_h2_one_s1_chipselect),                    //                                       .chipselect
		.h2_ten_s1_address                            (mm_interconnect_0_h2_ten_s1_address),                       //                              h2_ten_s1.address
		.h2_ten_s1_write                              (mm_interconnect_0_h2_ten_s1_write),                         //                                       .write
		.h2_ten_s1_readdata                           (mm_interconnect_0_h2_ten_s1_readdata),                      //                                       .readdata
		.h2_ten_s1_writedata                          (mm_interconnect_0_h2_ten_s1_writedata),                     //                                       .writedata
		.h2_ten_s1_chipselect                         (mm_interconnect_0_h2_ten_s1_chipselect),                    //                                       .chipselect
		.harmful_one_s1_address                       (mm_interconnect_0_harmful_one_s1_address),                  //                         harmful_one_s1.address
		.harmful_one_s1_write                         (mm_interconnect_0_harmful_one_s1_write),                    //                                       .write
		.harmful_one_s1_readdata                      (mm_interconnect_0_harmful_one_s1_readdata),                 //                                       .readdata
		.harmful_one_s1_writedata                     (mm_interconnect_0_harmful_one_s1_writedata),                //                                       .writedata
		.harmful_one_s1_chipselect                    (mm_interconnect_0_harmful_one_s1_chipselect),               //                                       .chipselect
		.harmful_ten_s1_address                       (mm_interconnect_0_harmful_ten_s1_address),                  //                         harmful_ten_s1.address
		.harmful_ten_s1_write                         (mm_interconnect_0_harmful_ten_s1_write),                    //                                       .write
		.harmful_ten_s1_readdata                      (mm_interconnect_0_harmful_ten_s1_readdata),                 //                                       .readdata
		.harmful_ten_s1_writedata                     (mm_interconnect_0_harmful_ten_s1_writedata),                //                                       .writedata
		.harmful_ten_s1_chipselect                    (mm_interconnect_0_harmful_ten_s1_chipselect),               //                                       .chipselect
		.heart_rate_hun_s1_address                    (mm_interconnect_0_heart_rate_hun_s1_address),               //                      heart_rate_hun_s1.address
		.heart_rate_hun_s1_write                      (mm_interconnect_0_heart_rate_hun_s1_write),                 //                                       .write
		.heart_rate_hun_s1_readdata                   (mm_interconnect_0_heart_rate_hun_s1_readdata),              //                                       .readdata
		.heart_rate_hun_s1_writedata                  (mm_interconnect_0_heart_rate_hun_s1_writedata),             //                                       .writedata
		.heart_rate_hun_s1_chipselect                 (mm_interconnect_0_heart_rate_hun_s1_chipselect),            //                                       .chipselect
		.heart_rate_one_s1_address                    (mm_interconnect_0_heart_rate_one_s1_address),               //                      heart_rate_one_s1.address
		.heart_rate_one_s1_write                      (mm_interconnect_0_heart_rate_one_s1_write),                 //                                       .write
		.heart_rate_one_s1_readdata                   (mm_interconnect_0_heart_rate_one_s1_readdata),              //                                       .readdata
		.heart_rate_one_s1_writedata                  (mm_interconnect_0_heart_rate_one_s1_writedata),             //                                       .writedata
		.heart_rate_one_s1_chipselect                 (mm_interconnect_0_heart_rate_one_s1_chipselect),            //                                       .chipselect
		.heart_rate_ten_s1_address                    (mm_interconnect_0_heart_rate_ten_s1_address),               //                      heart_rate_ten_s1.address
		.heart_rate_ten_s1_write                      (mm_interconnect_0_heart_rate_ten_s1_write),                 //                                       .write
		.heart_rate_ten_s1_readdata                   (mm_interconnect_0_heart_rate_ten_s1_readdata),              //                                       .readdata
		.heart_rate_ten_s1_writedata                  (mm_interconnect_0_heart_rate_ten_s1_writedata),             //                                       .writedata
		.heart_rate_ten_s1_chipselect                 (mm_interconnect_0_heart_rate_ten_s1_chipselect),            //                                       .chipselect
		.jtag_uart_avalon_jtag_slave_address          (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //            jtag_uart_avalon_jtag_slave.address
		.jtag_uart_avalon_jtag_slave_write            (mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),       //                                       .write
		.jtag_uart_avalon_jtag_slave_read             (mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),        //                                       .read
		.jtag_uart_avalon_jtag_slave_readdata         (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                                       .readdata
		.jtag_uart_avalon_jtag_slave_writedata        (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                                       .writedata
		.jtag_uart_avalon_jtag_slave_waitrequest      (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                                       .waitrequest
		.jtag_uart_avalon_jtag_slave_chipselect       (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  //                                       .chipselect
		.liquefied_one_s1_address                     (mm_interconnect_0_liquefied_one_s1_address),                //                       liquefied_one_s1.address
		.liquefied_one_s1_write                       (mm_interconnect_0_liquefied_one_s1_write),                  //                                       .write
		.liquefied_one_s1_readdata                    (mm_interconnect_0_liquefied_one_s1_readdata),               //                                       .readdata
		.liquefied_one_s1_writedata                   (mm_interconnect_0_liquefied_one_s1_writedata),              //                                       .writedata
		.liquefied_one_s1_chipselect                  (mm_interconnect_0_liquefied_one_s1_chipselect),             //                                       .chipselect
		.liquefied_ten_s1_address                     (mm_interconnect_0_liquefied_ten_s1_address),                //                       liquefied_ten_s1.address
		.liquefied_ten_s1_write                       (mm_interconnect_0_liquefied_ten_s1_write),                  //                                       .write
		.liquefied_ten_s1_readdata                    (mm_interconnect_0_liquefied_ten_s1_readdata),               //                                       .readdata
		.liquefied_ten_s1_writedata                   (mm_interconnect_0_liquefied_ten_s1_writedata),              //                                       .writedata
		.liquefied_ten_s1_chipselect                  (mm_interconnect_0_liquefied_ten_s1_chipselect),             //                                       .chipselect
		.max30102_0_s1_address                        (mm_interconnect_0_max30102_0_s1_address),                   //                          max30102_0_s1.address
		.max30102_0_s1_readdata                       (mm_interconnect_0_max30102_0_s1_readdata),                  //                                       .readdata
		.max30102_1_s1_address                        (mm_interconnect_0_max30102_1_s1_address),                   //                          max30102_1_s1.address
		.max30102_1_s1_readdata                       (mm_interconnect_0_max30102_1_s1_readdata),                  //                                       .readdata
		.natural_one_s1_address                       (mm_interconnect_0_natural_one_s1_address),                  //                         natural_one_s1.address
		.natural_one_s1_write                         (mm_interconnect_0_natural_one_s1_write),                    //                                       .write
		.natural_one_s1_readdata                      (mm_interconnect_0_natural_one_s1_readdata),                 //                                       .readdata
		.natural_one_s1_writedata                     (mm_interconnect_0_natural_one_s1_writedata),                //                                       .writedata
		.natural_one_s1_chipselect                    (mm_interconnect_0_natural_one_s1_chipselect),               //                                       .chipselect
		.natural_ten_s1_address                       (mm_interconnect_0_natural_ten_s1_address),                  //                         natural_ten_s1.address
		.natural_ten_s1_write                         (mm_interconnect_0_natural_ten_s1_write),                    //                                       .write
		.natural_ten_s1_readdata                      (mm_interconnect_0_natural_ten_s1_readdata),                 //                                       .readdata
		.natural_ten_s1_writedata                     (mm_interconnect_0_natural_ten_s1_writedata),                //                                       .writedata
		.natural_ten_s1_chipselect                    (mm_interconnect_0_natural_ten_s1_chipselect),               //                                       .chipselect
		.nios2_gen2_debug_mem_slave_address           (mm_interconnect_0_nios2_gen2_debug_mem_slave_address),      //             nios2_gen2_debug_mem_slave.address
		.nios2_gen2_debug_mem_slave_write             (mm_interconnect_0_nios2_gen2_debug_mem_slave_write),        //                                       .write
		.nios2_gen2_debug_mem_slave_read              (mm_interconnect_0_nios2_gen2_debug_mem_slave_read),         //                                       .read
		.nios2_gen2_debug_mem_slave_readdata          (mm_interconnect_0_nios2_gen2_debug_mem_slave_readdata),     //                                       .readdata
		.nios2_gen2_debug_mem_slave_writedata         (mm_interconnect_0_nios2_gen2_debug_mem_slave_writedata),    //                                       .writedata
		.nios2_gen2_debug_mem_slave_byteenable        (mm_interconnect_0_nios2_gen2_debug_mem_slave_byteenable),   //                                       .byteenable
		.nios2_gen2_debug_mem_slave_waitrequest       (mm_interconnect_0_nios2_gen2_debug_mem_slave_waitrequest),  //                                       .waitrequest
		.nios2_gen2_debug_mem_slave_debugaccess       (mm_interconnect_0_nios2_gen2_debug_mem_slave_debugaccess),  //                                       .debugaccess
		.oxy_one_s1_address                           (mm_interconnect_0_oxy_one_s1_address),                      //                             oxy_one_s1.address
		.oxy_one_s1_write                             (mm_interconnect_0_oxy_one_s1_write),                        //                                       .write
		.oxy_one_s1_readdata                          (mm_interconnect_0_oxy_one_s1_readdata),                     //                                       .readdata
		.oxy_one_s1_writedata                         (mm_interconnect_0_oxy_one_s1_writedata),                    //                                       .writedata
		.oxy_one_s1_chipselect                        (mm_interconnect_0_oxy_one_s1_chipselect),                   //                                       .chipselect
		.oxy_ten_s1_address                           (mm_interconnect_0_oxy_ten_s1_address),                      //                             oxy_ten_s1.address
		.oxy_ten_s1_write                             (mm_interconnect_0_oxy_ten_s1_write),                        //                                       .write
		.oxy_ten_s1_readdata                          (mm_interconnect_0_oxy_ten_s1_readdata),                     //                                       .readdata
		.oxy_ten_s1_writedata                         (mm_interconnect_0_oxy_ten_s1_writedata),                    //                                       .writedata
		.oxy_ten_s1_chipselect                        (mm_interconnect_0_oxy_ten_s1_chipselect),                   //                                       .chipselect
		.RAM_s1_address                               (mm_interconnect_0_ram_s1_address),                          //                                 RAM_s1.address
		.RAM_s1_write                                 (mm_interconnect_0_ram_s1_write),                            //                                       .write
		.RAM_s1_readdata                              (mm_interconnect_0_ram_s1_readdata),                         //                                       .readdata
		.RAM_s1_writedata                             (mm_interconnect_0_ram_s1_writedata),                        //                                       .writedata
		.RAM_s1_byteenable                            (mm_interconnect_0_ram_s1_byteenable),                       //                                       .byteenable
		.RAM_s1_chipselect                            (mm_interconnect_0_ram_s1_chipselect),                       //                                       .chipselect
		.RAM_s1_clken                                 (mm_interconnect_0_ram_s1_clken),                            //                                       .clken
		.ROM_s1_address                               (mm_interconnect_0_rom_s1_address),                          //                                 ROM_s1.address
		.ROM_s1_write                                 (mm_interconnect_0_rom_s1_write),                            //                                       .write
		.ROM_s1_readdata                              (mm_interconnect_0_rom_s1_readdata),                         //                                       .readdata
		.ROM_s1_writedata                             (mm_interconnect_0_rom_s1_writedata),                        //                                       .writedata
		.ROM_s1_byteenable                            (mm_interconnect_0_rom_s1_byteenable),                       //                                       .byteenable
		.ROM_s1_chipselect                            (mm_interconnect_0_rom_s1_chipselect),                       //                                       .chipselect
		.ROM_s1_clken                                 (mm_interconnect_0_rom_s1_clken),                            //                                       .clken
		.ROM_s1_debugaccess                           (mm_interconnect_0_rom_s1_debugaccess),                      //                                       .debugaccess
		.sysid_qsys_control_slave_address             (mm_interconnect_0_sysid_qsys_control_slave_address),        //               sysid_qsys_control_slave.address
		.sysid_qsys_control_slave_readdata            (mm_interconnect_0_sysid_qsys_control_slave_readdata)        //                                       .readdata
	);

	qsys_system_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (nios2_gen2_irq_irq)              //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                       // reset_in0.reset
		.reset_in1      (nios2_gen2_debug_reset_request_reset), // reset_in1.reset
		.clk            (clk_clk),                              //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),       // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req),   //          .reset_req
		.reset_req_in0  (1'b0),                                 // (terminated)
		.reset_req_in1  (1'b0),                                 // (terminated)
		.reset_in2      (1'b0),                                 // (terminated)
		.reset_req_in2  (1'b0),                                 // (terminated)
		.reset_in3      (1'b0),                                 // (terminated)
		.reset_req_in3  (1'b0),                                 // (terminated)
		.reset_in4      (1'b0),                                 // (terminated)
		.reset_req_in4  (1'b0),                                 // (terminated)
		.reset_in5      (1'b0),                                 // (terminated)
		.reset_req_in5  (1'b0),                                 // (terminated)
		.reset_in6      (1'b0),                                 // (terminated)
		.reset_req_in6  (1'b0),                                 // (terminated)
		.reset_in7      (1'b0),                                 // (terminated)
		.reset_req_in7  (1'b0),                                 // (terminated)
		.reset_in8      (1'b0),                                 // (terminated)
		.reset_req_in8  (1'b0),                                 // (terminated)
		.reset_in9      (1'b0),                                 // (terminated)
		.reset_req_in9  (1'b0),                                 // (terminated)
		.reset_in10     (1'b0),                                 // (terminated)
		.reset_req_in10 (1'b0),                                 // (terminated)
		.reset_in11     (1'b0),                                 // (terminated)
		.reset_req_in11 (1'b0),                                 // (terminated)
		.reset_in12     (1'b0),                                 // (terminated)
		.reset_req_in12 (1'b0),                                 // (terminated)
		.reset_in13     (1'b0),                                 // (terminated)
		.reset_req_in13 (1'b0),                                 // (terminated)
		.reset_in14     (1'b0),                                 // (terminated)
		.reset_req_in14 (1'b0),                                 // (terminated)
		.reset_in15     (1'b0),                                 // (terminated)
		.reset_req_in15 (1'b0)                                  // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                         // reset_in0.reset
		.clk            (clk_clk),                                //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_001_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_in1      (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

endmodule
